### ISSUE TITLE
Uploader - fix window build

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon-uploader#210]
During the tests for the Windows uploader, we found that some of the test cases were failed. The user cannot see the Windows uploader popup with the latest version of Uploader App.

Details:
Hi guys! I’ve got a feedback related to auto-update windows version of Uploader from Noon, Art and Frongs. Noon has successful result, Art and Frongs have a problem with updating Windows version, and these issues are different:
Art’s squirrel file log rfcx-ingest-1.5.6-delta.nupkg- File contains corrupted data
2024-03-12 23:23:48> CheckForUpdateImpl: Downloading RELEASES file from https://ingest.rfcx.org/update/win32_x64/1.5.5
2024-03-12 23:23:49> FileDownloader: Downloading url: https://ingest.rfcx.org/update/win32_x64/1.5.5/RELEASES?id=rfcx-ingest&localVersion=1.5.5&arch=amd64
2024-03-12 23:23:52> UpdateInfo: Couldn't get release notes for:rfcx-ingest-1.5.6-delta.nupkg: System.IO.FileFormatException: File contains corrupted data.
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
Frongs’s squirrel file log: rfcx-ingest-1.5.6-full.nupkg - Could not find file 'C:\Users\frong\AppData\Local\rfcx-ingest\packages\rfcx-ingest-1.5.6-full.nupkg
2024-03-13 00:38:01> FileDownloader: Downloading url: https://ingest.rfcx.org/update/win32_x64/1.5.1/RELEASES?id=rfcx-ingest&localVersion=1.5.1&arch=amd64
2024-03-13 00:38:04> UpdateInfo: Couldn't get release notes for:rfcx-ingest-1.5.6-full.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\frong\AppData\Local\rfcx-ingest\packages\rfcx-ingest-1.5.6-full.nupkg'.
File name: 'C:\Users\frong\AppData\Local\rfcx-ingest\packages\rfcx-ingest-1.5.6-full.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at NuGet.ZipPackage..ctor(String filePath, Boolean enableCaching)
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
Finally, Frongs can see new styles, but Art still cannot see them.
I guess we need to remove the tag and rebuild the version tomorrow morning

**Comment by rassokhina-e** [comment]
We have to test with a new version

**Comment by koonchaya** [comment]
@rassokhina-e Can you update the color in these places
- custom filename format
- pause button (bottom left of the app)
- double check failed icon color (bottom left of the app)


![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/b0547085-bad4-4ae9-8682-7fa943decf79)



![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/6cf42d67-e8b3-47f0-aedb-e7e923fc072e)

**Comment by koonchaya** [comment]
@rassokhina-e what is the next step?

**Comment by koonchaya** [comment]
Zhenya will have to rebuild window version and test it.

**Comment by rassokhina-e** [comment]
The problem with the drivelist, the 9 version which we use is not supported now, the lates versions don't work with Node 14, I've tried to decrease the drivelist to 6 version. Lets check the build and auto-update then.




![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/ccead4d1-47e3-4654-ab56-6f31406bfa0f)

**Comment by naluinui** [comment]
Related eng-support issue convo: https://rfcx.slack.com/archives/C03FD1WD02J/p1714663841690729

We'll need to keep the user posted once this is fixed

**Comment by koonchaya** [comment]
Created a new ticket to fix the auto update https://github.com/rfcx/arbimon-uploader/issues/221
